site_name: Cambigo Documentation
# docs_dir: ../your_docs_dir
repo_url: https://github.com/Cambigo/docs
site_url: https://docs.cambigo.com/
repo_name: Cambigo/docs
edit_uri: blob/main/docs/
theme:
  name: material
  logo: static/img/cambigo-logo-b.png
  favicon: static/img/cambigo-logo-icon-bw.png
  # custom_dir: custom_templates
  palette:
    primary: brown
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.tabs
    - navigation.top
    - search.highlight
    - toc.follow
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - sql

plugins:
  - search
  - awesome-nav

extra_css:
  - static/css/adjust.css
extra_javascript:
  - static/js/main.js
  - static/js/d3.v7.min.js

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true


exclude_docs: |
  __*.md
draft_docs: |
  DRAFT_*.md

extra:
  generator: false