name: Deploy Cambigo Flow Documentation

on:
  push:
    branches: ["main", "dev"]
  schedule:
    - cron: '0 0 * * 1,4'  # 6PM CST on Monday and Thursday (12AM UTC)
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code.
      uses: actions/checkout@v3
    - name: Check environment.
      run: |
        ls -ltra
        python --version
        pip --version
    - name: Fetch known issues and update releases page
      uses: ./.github/actions/known-issues
      with:
        github-token: ${{ secrets.ISSUES }}
        repository: 'Cambigo/ala'
        label: 'known issue'
        releases-file: 'docs/releases.md'
    - name: Install dependencies.
      run: |
        pip install -r requirements.txt
    - name: Run python script.
      run: |
        mkdocs build
    - name: Package site.
      uses: actions/upload-artifact@v4
      with:
        name: notebook-site
        path: |
          site
  deploy:
    # Only run deploy job on main branch
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Site.
        uses: actions/download-artifact@v4
        with:
          name: notebook-site
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4